services:
  - name: auth-service
    type: web
    runtime: node
    rootDir: auth-service
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        value: postgresql://postgres.ygjfrmzbvgznzdjpdsff:UGQoOCmFRolctC6V@aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres
      - key: JWT_SECRET
        value: afb0e06e2e3032569677a86776dd9b5c8525ab6d8a04b3eeb8cd28ad645ef36aa456dd94cb50eeb80dfde46a1ae898c23d2216770cd8b9305bfec238727ad831
      - key: JWT_REFRESH_SECRET
        value: c86c2d5a322409c78f5d260bba8c914123b04adc51ba8b774bcdfb58c7e54feabcee0386d5c615d1fc5d4954d059e84c7590db5b068addaf242e2de5ba0cf640
      - key: JWT_EXPIRES_IN
        value: 7d

  - name: business-service
    type: web
    runtime: node
    rootDir: business-service
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002
      - key: DATABASE_URL
        value: postgresql://postgres.ygjfrmzbvgznzdjpdsff:UGQoOCmFRolctC6V@aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres
      - key: JWT_SECRET
        value: afb0e06e2e3032569677a86776dd9b5c8525ab6d8a04b3eeb8cd28ad645ef36aa456dd94cb50eeb80dfde46a1ae898c23d2216770cd8b9305bfec238727ad831
      - key: JWT_REFRESH_SECRET
        value: c86c2d5a322409c78f5d260bba8c914123b04adc51ba8b774bcdfb58c7e54feabcee0386d5c615d1fc5d4954d059e84c7590db5b068addaf242e2de5ba0cf640

  - name: billing-service
    type: web
    runtime: node
    rootDir: billing-service
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3003
      - key: DATABASE_URL
        value: postgresql://postgres.ygjfrmzbvgznzdjpdsff:UGQoOCmFRolctC6V@aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres
      - key: JWT_SECRET
        value: afb0e06e2e3032569677a86776dd9b5c8525ab6d8a04b3eeb8cd28ad645ef36aa456dd94cb50eeb80dfde46a1ae898c23d2216770cd8b9305bfec238727ad831
      - key: JWT_REFRESH_SECRET
        value: c86c2d5a322409c78f5d260bba8c914123b04adc51ba8b774bcdfb58c7e54feabcee0386d5c615d1fc5d4954d059e84c7590db5b068addaf242e2de5ba0cf640

  - name: api-gateway
    type: web
    runtime: node
    rootDir: api-gateway
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: AUTH_SERVICE_URL
        value: https://auth-service-015z.onrender.com
      - key: BUSINESS_SERVICE_URL
        value: https://nava-nava-vyapaar.onrender.com
      - key: BILLING_SERVICE_URL
        value: https://billing-service-td7u.onrender.com
